<?php
require_once 'model.php';
/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-01-12 at 17:54:09.
 */
class Index_ModelTest extends PHPUnit_Framework_TestCase {

    /**
     * @var Index_Model
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Index_Model;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

}
