<?php
require_once 'model.php';
/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-01-12 at 17:54:10.
 */
class The_Image_Model_ResolverTest extends PHPUnit_Framework_TestCase {

    /**
     * @var The_Image_Model_Resolver
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new The_Image_Model_Resolver;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers The_Image_Model_Resolver::indexToName
     * @todo   Implement testIndexToName().
     */
    public function testIndexToName() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers The_Image_Model_Resolver::nameToIndex
     * @todo   Implement testNameToIndex().
     */
    public function testNameToIndex() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
