<?php if (empty($o)) die('Can\'t execute.'); ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" 
  "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <?php require('chunks/html_head.phtml'); ?>
    <?php @include('custom/header.php'); ?>
</head>
<body>
    <div class ="com_wrapper">
        <?php require('chunks/header.phtml');?>
        <?php require('chunks/comicLink.phtml');?>
        <?php require('chunks/otherLangs.phtml');?>
	<div class="com_body">
		
		<?php require('chunks/elements.phtml'); ?>
		
	</div>
        
        <?php @include('custom/content.php'); ?>
        <?php @include('custom/comments.php'); ?>
        <?php @include('custom/content-bottom.php'); ?>
        <?php @include('custom/footer.php'); ?>
    </div>
</body>
</html>