<?php if (empty($o)) die('Can\'t execute.'); ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" 
  "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<?php require('chunks/html_head.phtml'); ?>
<body>
    <div class ="com_wrapper">
	<?php require('chunks/header.phtml');?>
	
        <div class="com_body">
		<?php require('chunks/image.phtml'); ?>
		
		<?php require('chunks/elements.phtml'); ?>
		
	</div>
    </div>
</body>
</html>