<?php if (empty($o)) die('Can\'t execute.'); ?> 
               <?php if ( !SINGLE_COMIC_MODE && $o->descr('dir')):?>
               
			<a href="<?php echo $o->descr('dir')?>" id="up_page">
				<h2><?php echo $o->title(); ?></h2>
			</a>
		
		<?php else:?>
			<a href="<?php echo $o->homeUrl(); ?>">
                            <h2><?php echo $o->title(); ?></h2>
                        </a>
		
		<?php endif;?>
