<?php if (empty($o)) die('Can\'t execute.'); ?> 

        <?php if($o->hasElements()):?>
            <table class="com_main_frame">
                <tr>
                    <td>
                        <?php include('prevButton.phtml'); ?>
                    </td>
                    <td>
                        <div id="com_id_elements" class="com_elements">
                            <?php while( ($book = $o->nextElement()) ): ?>
                                    <div class="com_el">
                                            <?php if (isset($book['dir'])):?>
                                                    <h3>
                                                            <a href='<?php echo $o->currentDir() . $book['dir']?>' >
                                                                    <?php echo $book['title'] ?>
                                                            </a>
                                                    </h3>

                                                    <?php if (!empty($book['cover'])):?>
                                                            <a href='<?php echo $o->currentDir() . $book['dir']?>' >
                                                                    <img src='<?php echo $o->thumb($book['cover']);?>' />
                                                            </a>
                                                    <?php endif;?>
                                            <?php endif; ?>

                                            <?php if ( !empty($book['path']) && !empty($book['filename']) ):?>
                                                    <a href='<?php echo $l->href($book); ?>' >							
                                                                    <img src='<?php echo $o->thumb($book['path']);?>' />
                                                    </a>
                                            <?php endif; ?>

                                            <?php if (!empty($book['languages'])):?>
                                                    <ul>
                                                    <?php for($lang = 0; $lang < count($book['languages']); $lang++): ?>
                                                            <li><a href='<?php echo $book['dir'] . $book['languages'][$lang] . '/' ?>'><?php echo $book['languages'][$lang]?></a></li>
                                                    <?php endfor;?>
                                                    </ul>
                                            <?php endif; ?>
                                            <?php if ( $o->safeGet($book,'isNew') ):?>
                                                <p>New</p>
                                            <?php endif;?>
                                    </div>
                            <?php endwhile; ?>
                            <hr class="cleaner" />
                        </div>
                    </td>
                    <td>
                        <?php include('nextButton.phtml'); ?>
                    </td>
                </tr>
            </table>  
        <?php endif; ?>
	
        <?php require('paging.phtml');?>
            