<?php if (empty($o)) die('Can\'t execute.'); ?>

<?php if ( ($image = $o->extra('image')) ): ?>
    <div class="com_image">	
        <?php if( ($btn = $o->extra('buttons') ) && false !== $btn['next']):?>
            <a href='<?php echo $l->href($btn['next']) ?>'>
                <img src='<?php echo $o->homeUrl() . $image['path']?>' \>
            </a>
        
        <?php elseif ( $o->safeGet($o->extra('neighbors'),'nextDir') ): ?>
            <a href='<?php echo $l->href($o->safeGet($o->extra('neighbors'),'nextDir')) ?>'>
                <img src='<?php echo $o->homeUrl() . $image['path']?>' \>
            </a>
        
        <?php else:?>
            <img src='<?php echo $o->homeUrl() . $image['path']?>' \>
        <?php endif;?>
    </div>
<?php endif; ?>