<?php if (empty($o)) die('Can\'t execute.'); ?> 

<?php if ( ($btns = $o->extra('buttons')) && count($btns['pages']) > 1 && isset($btns['next'])):?>

    <?php if ( !USE_AJAX_CHAPTER || !$o->extra('ajax') ):?>

        <?php if(false !== $btns['next']):?>
            <a href='<?php echo $l->href($btns['next']) ?>' id="next_page">
                <?php echo $o->translate('next');?>
            </a>&nbsp;
        <?php endif;?>

    <?php else: ?>
        
        <a id="next_page" href='<?php echo ( ($btns['next']) ? $l->href($btns['next']) : $l->getCurrentDir() )  ?>' <?php if (empty($btns['next'])) echo ' style="display:none;"' ?>>
            <?php echo $o->translate('next');?>
	</a>
            
    <?php endif; ?>

<?php endif; ?> 

