<?php if (empty($o)) die('Can\'t execute.'); ?> 
	<?php /*var_dump($model);*/ ?>
	
<?php if ( ($btns = $o->extra('buttons')) && count($btns['pages']) > 1):?>
	<div class="com_navigation">
		<?php for($i=0; !empty($btns['pages']) && count($btns['pages']) > 1 && $i<count($btns['pages']); $i++):?>
			<?php if(isset($btns['current']) && $btns['pages'][$i]['id'] == $btns['current']): ?>
			
				<a href='<?php echo (($btns['pages'][$i]) ? $l->href($btns['pages'][$i]) : $l->getCurrentDir()) ; ?>' title="<?php echo  ($i + 1); ?>" class='nav_button active_page'>
					<span class='com_page_number'><?php echo  ($i + 1); ?></span>
                                        <span class='com_page_circle'><?php echo NAV_PAGE_SYMBOL ?></span>
				</a> &nbsp;
			
			<?php else: ?>
			
				<a href='<?php echo (($btns['pages'][$i]) ? $l->href($btns['pages'][$i]) : $l->getCurrentDir()) ; ?>' title="<?php echo  ($i + 1); ?>" class='nav_button'>
					<span class='com_page_number'><?php echo  ($i + 1); ?></span>
                                        <span class='com_page_circle'><?php echo NAV_PAGE_SYMBOL ?></span>
				</a> &nbsp;
			
			<?php endif;?>
		<?php endfor; ?>        
	</div>
<?php endif;?>	
	