<?php if (empty($o)) die('Can\'t execute.'); ?> 

<?php if ( ($btns = $o->extra('buttons')) && count($btns['pages']) > 1 && isset($btns['prev']) ):?>

    <?php if ( !USE_AJAX_CHAPTER  || !$o->extra('ajax') ):?>

        <?php if(false !== $btns['prev']):?>
            <a href='<?php echo (($btns['prev']) ? $l->href($btns['prev']) : $l->getCurrentDir() ) ; ?>' id="previous_page">
                <?php echo $o->translate('prev');?>
            </a>&nbsp;
        <?php endif;?>

    <?php else: ?>
        
        <a id="previous_page" href='<?php echo ( ($btns['prev']) ? $l->href($btns['prev']) : $l->getCurrentDir() ) ?>' <?php if (false === $btns['prev']) echo ' style="display:none;"' ?>>
            <?php echo $o->translate('prev');?>
	</a>
            
    <?php endif; ?>

<?php endif; ?>

