<?php
require_once 'comic_view.php';

class Comic_ViewWrapper extends Comic_View
{
    protected function buildHTMLImpl($data, $link){
        
    } 
}

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-01-05 at 17:12:19.
 */
class Comic_ViewTest extends PHPUnit_Framework_TestCase {

    /**
     * @var Comic_View
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Comic_ViewWrapper;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers Comic_View::cache
     * @todo   Implement testCache().
     */
    public function testCache() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Comic_View::hasCache
     * @todo   Implement testHasCache().
     */
    public function testHasCache() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Comic_View::displayFromCache
     * @todo   Implement testDisplayFromCache().
     */
    public function testDisplayFromCache() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Comic_View::display
     * @todo   Implement testDisplay().
     */
    public function testDisplay() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
