<?php
require_once 'comic_view.php';
/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-01-05 at 17:12:19.
 */
class HTMLProviderTest extends PHPUnit_Framework_TestCase {

    /**
     * @var HTMLProvider
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new HTMLProvider;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers HTMLProvider::title
     * @todo   Implement testTitle().
     */
    public function testTitle() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers HTMLProvider::homeUrl
     * @todo   Implement testHomeUrl().
     */
    public function testHomeUrl() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers HTMLProvider::domain
     * @todo   Implement testDomain().
     */
    public function testDomain() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers HTMLProvider::translate
     * @todo   Implement testTranslate().
     */
    public function testTranslate() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers HTMLProvider::thumb_abs
     * @todo   Implement testThumb_abs().
     */
    public function testThumb_abs() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers HTMLProvider::thumb
     * @todo   Implement testThumb().
     */
    public function testThumb() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers HTMLProvider::currentDir
     * @todo   Implement testCurrentDir().
     */
    public function testCurrentDir() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
