<?php
require_once 'entities.php';
/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-01-05 at 17:50:01.
 */
class Book_DescriptionTest extends PHPUnit_Framework_TestCase {

    /*
     * @covers  Book_Description::searchCover
     * @covers  Book_Description::imageExists
     * @covers  Book_Description::__construct
     * 
     */
    public function testCtor() {
       @unlink('book_descr/the_book/cover.jpg');
       @rmdir('book_descr/the_book/en');
       @rmdir('book_descr/the_book/ru');
       @rmdir('book_descr/the_book/');
       @rmdir('book_descr'); 
       
       mkdir('book_descr');
       mkdir('book_descr/the_book');
       mkdir('book_descr/the_book/en');
       mkdir('book_descr/the_book/ru');
       
       $obj = new Book_Description('book_descr/the_book/');
       $this->assertEquals('the_book/',$obj->dir);
       $this->assertEquals('The Book',$obj->title);
       $this->assertEquals('the_book/',$obj->dir);
       $this->assertEquals(array('en','ru'),$obj->languages);
       $this->assertEquals(DEFAULT_COVER,$obj->cover);
       
       
       file_put_contents('book_descr/the_book/cover.jpg', 'ok');
       $obj2 = new Book_Description('book_descr/the_book/');
       $this->assertEquals('book_descr/the_book/cover.jpg',$obj2->cover);
       
       @unlink('book_descr/the_book/cover.jpg');
       @rmdir('book_descr/the_book/en');
       @rmdir('book_descr/the_book/ru');
       @rmdir('book_descr/the_book/');
       @rmdir('book_descr'); 
    }
            

}
