<?php
require_once 'entities.php';
/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-01-05 at 17:50:02.
 */
class Chapter_DescriptionTest extends PHPUnit_Framework_TestCase {

   /*
     * @covers  Chapter_Description::__construct
     * 
     */
    public function testCtor() {
        @unlink('ch_descr/the_book/en/00/01.png');
        @rmdir('ch_descr/the_book/en/00');
        @rmdir('ch_descr/the_book/en');
        @rmdir('ch_descr/the_book/');
        @rmdir('ch_descr'); 
        
        mkdir('ch_descr');
        mkdir('ch_descr/the_book');
        mkdir('ch_descr/the_book/en');
        mkdir('ch_descr/the_book/en/00');
        
        $obj = new Chapter_Description('ch_descr/the_book/en/00/');
        $this->assertEquals(DEFAULT_COVER,$obj->cover);
        
        file_put_contents('ch_descr/the_book/en/00/01.png', 'ok');
        $obj = new Chapter_Description('ch_descr/the_book/en/00/');
        $this->assertEquals('ch_descr/the_book/en/00/01.png',$obj->cover);
        
        @unlink('ch_descr/the_book/en/00/01.png');
        @rmdir('ch_descr/the_book/en/00');
        @rmdir('ch_descr/the_book/en');
        @rmdir('ch_descr/the_book/');
        @rmdir('ch_descr'); 
    }

}
