<?php

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-01-05 at 17:12:22.
 */
class DirBased_ModelTest extends PHPUnit_Framework_TestCase {

    /**
     * @var DirBased_Model
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        //$this->object = new DirBased_Model;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers DirBased_Model::getCurrentDir
     * @todo   Implement testGetCurrentDir().
     */
    public function testGetCurrentDir() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers DirBased_Model::getCachePath
     * @todo   Implement testGetCachePath().
     */
    public function testGetCachePath() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers DirBased_Model::serializeToArray
     * @todo   Implement testSerializeToArray().
     */
    public function testSerializeToArray() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
