<?php
require_once 'entities.php';
/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-01-05 at 17:50:00.
 */
class Image_DescriptionTest extends PHPUnit_Framework_TestCase {
    public function testCtor() {
        
        @unlink('ch_descr/the_book/en/00/01.png');
        @rmdir('ch_descr/the_book/en/00');
        @rmdir('ch_descr/the_book/en');
        @rmdir('ch_descr/the_book/');
        @rmdir('ch_descr'); 
        
        mkdir('ch_descr');
        mkdir('ch_descr/the_book');
        mkdir('ch_descr/the_book/en');
        mkdir('ch_descr/the_book/en/00');
        
        $obj = new Image_Description('ch_descr/the_book/en/00/01.png');
        $this->assertEquals('ch_descr/the_book/en/00/01.png',$obj->path);
        $this->assertEquals('01.png',$obj->filename);
        
        @unlink('ch_descr/the_book/en/00/01.png');
        @rmdir('ch_descr/the_book/en/00');
        @rmdir('ch_descr/the_book/en');
        @rmdir('ch_descr/the_book/');
        @rmdir('ch_descr'); 
    }
}
