<?php
require_once 'entities.php';
/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-01-05 at 17:50:02.
 */
class ItemTest extends PHPUnit_Framework_TestCase {

    /*
     * @covers Item::__construct
     */
    public function testCtor() {
        $obj = new Item(12);
        $this->assertEquals(12,$obj->id);
    }

}
