<?php

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-01-05 at 17:12:22.
 */
class MultiLang_ModelTest extends PHPUnit_Framework_TestCase {

    /**
     * @var MultiLang_Model
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        //$this->object = new MultiLang_Model;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers MultiLang_Model::getCurrentLanguage
     * @todo   Implement testGetCurrentLanguage().
     */
    public function testGetCurrentLanguage() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
